# Generated by Django 2.2.14 on 2022-10-26 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
        ('states', '0002_stateticket'),
        ('locations', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_1', to=settings.AUTH_USER_MODEL)),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('document', models.CharField(max_length=50)),
                ('cell_phone', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='customer_image')),
                ('url', models.CharField(max_length=100)),
                ('office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Office')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='states.State')),
            ],
        ),
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TypeFuncionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('flag', models.BooleanField(default=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Connection')),
                ('transmitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HelpDesk',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('document', models.CharField(max_length=50)),
                ('cell_phone', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='helpdesk_image')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='states.State')),
                ('type_document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.TypeDocument')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionary',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('document', models.CharField(max_length=50)),
                ('cell_phone', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='funcionary_image')),
                ('address', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Customer')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='states.State')),
                ('type_document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.TypeDocument')),
                ('type_funcionary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.TypeFuncionary')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='type_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.TypeDocument'),
        ),
    ]
