# Generated by Django 2.2.14 on 2022-11-09 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20221026_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='states.State'),
        ),
        migrations.AlterField(
            model_name='funcionary',
            name='state',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='states.State'),
        ),
        migrations.AlterField(
            model_name='helpdesk',
            name='state',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='states.State'),
        ),
    ]
